// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eydsaysgzspmlwwbasrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZHNheXNnenNwbWx3d2Jhc3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDY3NzUsImV4cCI6MjA2NDUyMjc3NX0.3GWSnXyxogh5fmERQEfhtgISb1vsgTM28qi0OODEh60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);